#!/usr/bin/env python3
"""
================================================================================
PROJECT SUTRA — KAGGLE GPU TARGET INGESTION & SWARM RETASKING BRIDGE
================================================================================
Author: Tech Lead Nikhil & Vedanth Sai Ram
Target: Smart Horizon Grand Finals (SH-DST-05)

PURPOSE:
  Reads confirmed perception detections generated by Kaggle GPU
  (kaggle_perception_results/sutra_canopy_detections.json) and streams them
  directly into ROS 2 topics:
    - /sutra/perception/targets   (for Subsystem A GNC Swarm Retasking)
    - /sutra/gcs/alerts           (for Subsystem D 3D GIS GCS HUD)

  Triggers real-time transition of all 5 SUTRA Pegasus UAVs from linear search
  into TACTICAL CONCENTRIC ORBIT surrounding detected ground survivors and vehicles!
================================================================================
"""

import os
import sys
import json
import time
from pathlib import Path

import rclpy
from rclpy.node import Node
from std_msgs.msg import String

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DETECTIONS_FILE = PROJECT_ROOT / "kaggle_perception_results/sutra_canopy_detections.json"


class KaggleTargetStreamerNode(Node):
    def __init__(self):
        super().__init__("sutra_kaggle_target_streamer")

        self.pub_targets = self.create_publisher(String, "/sutra/perception/targets", 10)
        self.pub_alerts = self.create_publisher(String, "/sutra/gcs/alerts", 10)

        if not DETECTIONS_FILE.exists():
            self.get_logger().error(f"❌ Detections manifest not found at: {DETECTIONS_FILE}")
            sys.exit(1)

        with open(DETECTIONS_FILE, "r") as f:
            self.manifest = json.load(f)

        self.targets = self.manifest.get("targets", [])
        self.target_idx = 0

        self.get_logger().info("==================================================================")
        self.get_logger().info("🎯 SUTRA KAGGLE GPU PERCEPTION STREAMER ONLINE")
        self.get_logger().info(f"   Hardware Origin : {self.manifest.get('gpu_hardware', 'Kaggle GPU')}")
        self.get_logger().info(f"   Loaded Targets  : {len(self.targets)} (4 Survivors, 1 Threat Vehicle)")
        self.get_logger().info("==================================================================")

        # Stream targets every 1.5s
        self.timer = self.create_timer(1.5, self._stream_target)

    def _stream_target(self):
        if not self.targets:
            return

        tgt = self.targets[self.target_idx]
        self.target_idx = (self.target_idx + 1) % len(self.targets)

        # 1. Publish confirmed target for GNC swarm orbit
        target_msg = String()
        target_msg.data = json.dumps({
            "status": "CONFIRMED",
            "source": "kaggle_gpu_perception",
            "targets": [tgt]
        })
        self.pub_targets.publish(target_msg)

        # 2. Publish alert badge for GCS HUD
        alert_msg = String()
        alert_msg.data = json.dumps({
            "type": "SURVIVOR_ALERT" if tgt["class_name"] == "Survivor" else "THREAT_ALERT",
            "target_id": tgt["target_code"],
            "class": tgt["class_name"],
            "confidence": tgt["confidence"],
            "wgs84": tgt["wgs84"],
            "ned": tgt["local_ned"],
            "timestamp": time.time()
        })
        self.pub_alerts.publish(alert_msg)

        label = tgt["class_name"]
        code = tgt["target_code"]
        conf = tgt["confidence"] * 100
        lat = tgt["wgs84"]["latitude"]
        lon = tgt["wgs84"]["longitude"]
        ned = tgt["local_ned"]

        self.get_logger().warn(
            f"📡 [Kaggle GPU → Swarm GNC] Streamed {label} {code} ({conf:.1f}%) | "
            f"NED: ({ned['x']:.2f}, {ned['y']:.2f}, {ned['z']:.2f})m | "
            f"WGS84: {lat:.6f}°N, {lon:.6f}°E"
        )


def main():
    rclpy.init()
    node = KaggleTargetStreamerNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
