name: Ground Control Station (GCS) CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'sutra_ws/src/sutra_gcs/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'sutra_ws/src/sutra_gcs/**'

jobs:
  gcs_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sutra_ws/src/sutra_gcs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node Dependencies
        run: npm install

      - name: Build GCS Dashboard
        run: npm run build
